<div id="block-<?php echo $this->blockId; ?>" class="region featured-exhibits <?php echo $this->classes; ?> <?php echo $this->regionClass; ?>" data-target-region-id="<?php echo $this->targetID; ?> ">
    <div class="featured-exhibits-intro">
        <?php if ($this->hasTitle || $this->hasIntroduction): ?>
            <div class='title-area'>
                <?php if ($this->hasTitle): ?>
                    <h2><?php echo $this->title; ?></h2>
                <?php endif; ?>
                <?php if ($this->hasIntroduction): ?>
                    <div class='block-introduction'>
                        <?php echo $this->introduction; ?>
                    </div>
                <?php endif; ?>
                <?php if ($this->hasButton): ?>
                    <?php printf('<a class="btn" href="%s" alt="%s">%s</a>',$this->buttonPath,$this->buttonText,$this->buttonText); ?>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>

    <?php $i=0; ?>

    <?php foreach($this->itemFields as $itemFieldSet): ?>
        <?php

        $item = isset($attachments[$i]) ? $attachments[$i]->item() : null;

        if (is_array($itemFieldSet)):
            ?>
            <div class="item resource link-card">
                <a title='<?php echo $this->itemFields[$i]["title"]; ?>' href='<?php echo $this->itemFields[$i]["url"]; ?>'>
                    <?php

                    if (!empty($this->itemFields[$i]["thumbnailUrl"])):
                        printf('<img src="%s" alt="%s" />',$this->itemFields[$i]["thumbnailUrl"],$this->itemFields[$i]["title"] . " Thumbnail");
                    elseif ($item):
                        $media = $attachments[$i]->media() ?: $item->primaryMedia();
                        if ($media):
                            echo $this->thumbnail($media, $this->thumbnailType); // $item->displayTitle()
                        endif;
                    endif;
                    ?>
                    <div class="link-card-info">
                        <?php if (!empty($this->itemFields[$i]["label"])): ?>
                            <div class='item-label'><?php echo  $this->itemFields[$i]["label"]; ?></div>
                        <?php endif; ?>
                        <h3><?php echo $this->itemFields[$i]["title"]; ?></h3>
                        <?php if (!empty($this->itemFields[$i]["subtitle"])): ?>
                            <div class='deck'><?php echo  $this->itemFields[$i]["subtitle"]; ?></div>
                        <?php endif; ?>
                        <hr>
                        <?php
                        $caption = !empty($this->itemFields[$i]["description"]) || !isset($attachments[$i]) ? $this->itemFields[$i]["description"] : $attachments[$i]->caption();
                        if ($caption):
                            ?>
                            <div class="description"><?php echo $caption; ?></div>
                        <?php endif; ?>
                        <a class='card-link' href='<?php echo $this->itemFields[$i]["url"]; ?>'>View Exhibit</a>
                    </div>
                </a></div>
        <?php endif; ?>
        <?php $i++; ?>
    <?php endforeach; ?>
</div>
